pool:
  vmImage: ubuntu-latest

steps:
- task: Npm@1
  displayName: "install packages"
  inputs:
    command: "install"

- task: Npm@1
  displayName: "build"
  inputs:
    command: "custom"
    customCommand: "run build"

- task: Npm@1
  displayName: "lint"
  inputs:
    command: "custom"
    customCommand: "run lint"
  condition: succeeded()

- task: Npm@1
  displayName: "test"
  inputs:
    command: "custom"
    customCommand: "run test -- --watchAll=false"
  condition: succeeded()
